name: chefkit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.1.1
  bloc: ^9.0.1
  lucide_icons: ^0.257.0
  equatable: ^2.0.7
  supabase: ^2.10.0
  dotenv: ^4.2.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  image_picker: ^1.2.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1
  path_provider: ^2.1.5
  get_it: ^9.2.0
  intl: ^0.20.2
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/ingredients/
    - assets/images/recipes/
    - assets/images/chefs/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900

    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Thin.ttf
          weight: 100
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Black.ttf
          weight: 900
