name: chefkit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  bloc: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins/Poppins-Black.ttf
        weight: 900

  - family: LeagueSpartan
    fonts:
      - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Thin.ttf
        weight: 100
      - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Light.ttf
        weight: 300
      - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Regular.ttf
        weight: 400
      - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Medium.ttf
        weight: 500
      - asset: assets/fonts/LeagueSpartan/LeagueSpartan-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Bold.ttf
        weight: 700
      - asset: assets/fonts/LeagueSpartan/LeagueSpartan-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Black.ttf
        weight: 900